import { defineStore } from 'pinia'

export interface LinkItem {
  name: string
  type: 'blog' | 'news' | 'github' | 'website' | 'paper'
  url: string
}

export interface TimelineItem {
  title: string
  organization: string
  period: string
  description?: string
  highlights?: string[]
  links?: LinkItem[]
  gpa?: string
}


export interface Patent {
  title: string
  authors: string
  number: string
}

export interface PressItem {
  title: string
  source: string
  link?: string
}

export interface ContactItem {
  type: 'email' | 'twitter' | 'linkedin' | 'github'
  value: string
  link?: string
}

export const useCVStore = defineStore('cv', {
  state: () => ({
    title: 'Research Scientist Manager at Google',
    professionalExperience: [
      {
        title: 'Research Scientist Manager',
        organization: 'Google Switzerland',
        period: '2020 - Present',
        description: 'Lead research in the Security Research Group at Google, focusing on designing better ways to protect people online, advancing cybersecurity through AI, and implementing hardware attacks and defenses.',
        highlights: [
          'Lead a team of researchers focusing on applied AI for security',
          'Contributed to SecGemini, an experimental AI model focused on cybersecurity',
          'Contributed to Magika, an AI-powered file type identification system',
          'Contributed to the implementation of Gmail spam and malware detection systems'
        ],
        links: [
          {
            name: 'Magika',
            type: 'website',
            url: '/projects#magika'
          },
          {
            name: 'SecGemini',
            type: 'website',
            url: '/projects#secgemini'
          }
        ]
      },
      {
        title: 'Senior Research Scientist',
        organization: 'Google US',
        period: '2016 - 2020',
        description: 'Conducted research in cybersecurity, focusing on botnet detection and takedown, internet measurements, and ransomware analysis.',
        highlights: [
          'Created automatic detection and disabling for leaked credentials',
          'Quantified revenue generated by ransomware attacks via cryptocurrency payments'
        ],
        links: [
          {
            name: 'Shattered',
            type: 'website',
            url: 'https://shattered.io/'
          }, {
            name: 'Ransomware',
            type: 'website',
            url: '/projects#ransomware'
          }
        ]
      },
      {
        title: 'Research Scientist',
        organization: 'Google US',
        period: '2015 - 2016',
        links: [{
            name: 'Cloaking paper',
            type: 'paper',
            url: 'https://ieeexplore.ieee.org/abstract/document/7546533'
        }],

        description: 'Joined Google\'s anti-abuse team to better understand and detect sophisticated cloaking sites.'
      },
      {
        title: 'Project Lead',
        organization: 'The Activity Exchange',
        period: '2012 - 2015',
        description: 'Led the design and running of a scalable service that collects, normalizes, and distributes sensitive health data from 20+ sources and 200k+ users, powering Achievemint.com and Humana Vitality.'
      },
      {
        title: 'Research Intern',
        organization: 'Narus',
        period: '2013',
        links: [
   
          {
            name: 'The Register',
            type: 'news',
            url: 'https://www.theregister.com/2014/02/18/zoom_out_for_a_view_of_malware_say_boffins/'
          }
        ],
        description: 'Designed Nazca, a system capable of discovering and tracking malicious downloads in the network traffic of ISPs. This work resulted in a NDSS\'14 paper, a patent, and sparked interest in the press.'
      },
      {
        title: 'Engineering Intern, Pentester',
        organization: 'Appfolio',
        period: '2011',
        description: 'Pentested various Ruby on Rails web apps, including a payment-processing system handling financial information of 100k+ users. Fixed various vulnerabilities and left the company with a set of tools integrated in their CI system to alert developers of potential security vulnerabilities.'
      },
      {
        title: 'Engineering Intern',
        organization: 'Google Summer of Code',
        period: '2010',
        description: 'Extended "Getting Things GNOME!", a task manager for the Linux desktop, to support multiple synchronization services such as Bugzilla, Evolution, and RememberTheMilk.'
      }
    ],
    education: [
    {
        title: "Executive Master of Business Administration",
        organization: "Quantic school of business and technology",
        period: '2018-2019',
        gpa: ' 95% with honors'
    },
      {
        title: 'Ph.D. in Computer Science, Information Security',
        organization: 'University of California, Santa Barbara',
        period: '2010 - 2015',
        description: 'Research focused on leveraging big-data analysis to discover malware distribution, improving Android security, maintaining privacy online, and teaching information security through hacking competitions.',
        highlights: [
          'UCSB Computer Science Outstanding Publication Award 2015',
          'CSAW best security paper 2012 finalist',
          'Secured $1.1M grant for Android security research'
        ],
        links: [
          {
            name: 'Campus Technology',
            type: 'news',
            url: 'https://campustechnology.com/articles/2014/09/18/ucsb-security-researchers-to-help-too-trusting-smartphone-app-users.aspx?admgarea=news'
          }
        ],
        gpa: '4.0/4.0'
      },
      {
        title: 'Master\'s in Computer Science',
        organization: 'University of California, Santa Barbara',
        period: '2010 - 2015',
        gpa: '4.0/4.0'
      },
      {
        title: 'Visiting Researcher',
        organization: 'University of Hawaii',
        period: '2009 - 2010',
        description: 'Worked on a novel mathematical model to drive autonomous underwater vehicles. This work was presented at the IEEE Conference on Decision and Control (CDC).'
      },
      {        title: 'Diploma di Licenza',
        organization: 'Sant\'Anna University, School of Advanced Studies, Italy',
        period: '2007 - 2010',
        gpa: '100/100 cum laude'
      },
      {
        title: 'Master\'s Degree in Control Engineering',
        organization: 'University of Pisa, Italy',
        period: '2007 - 2010',
        gpa: '110/110 cum laude',
      },
      
      {
        title: 'Visiting Researcher',
        organization: 'University of California, Santa Barbara',
        period: '2008',
        description: 'Worked on a distributed algorithm to drive autonomous land vehicles for area patrol in UCSB\'s mechanical engineering department. Part of this work is now in the Player/Stage open-source framework.'
      },
      {
        title: 'Bachelor\'s Degree in Computer Engineering',
        organization: 'University of Pisa, Italy',
        period: '2004 - 2007',
        gpa: '110/110 cum laude with excellence path'
      }
    ],
    openSourceContributions: [
      {
        title: 'Core Developer & Mentor',
        organization: 'The GNOME Foundation',
        period: '2010 - 2012',
        description: 'Core developer of "Getting Things GNOME" and member of the GNOME Foundation. Mentored five international students for several editions of the Google Summer of Code and the Gnome\'s Outreach Program for Women.',
        links: [
          {
            name: 'GNOME',
            type: 'website',
            url: 'https://www.gnome.org/'
          },
          {
            name: 'Getting Things GNOME',
            type: 'github',
            url: 'https://github.com/getting-things-gnome/gtg'
          }
        ]
      },
      {
        title: 'Open Source Contributor',
        organization: 'Various Projects',
        period: '2009 - Present',
        description: 'Created niche projects used by companies like Lastline and Google, including Scapy\'s support for HTTP and Chrisper (a style-checker for academic papers). Made contributions to popular open-source projects including PLAYER robotic framework, Flask-Security, and Eucalyptus.'
      }
    ],
    competitions: [
      {
        title: 'Hacking Competitions',
        organization: 'Shellphish Team',
        period: '2010 - 2015',
        links: [
            {
                name: 'CNBC',
                type: 'news',
                url: 'https://www.cnbc.com/2013/11/08/defcon-capture-the-flag-competition-is-only-for-top-hackers.html'
            },
            {
                name: 'SB Independent',
                type: 'news',
                url: 'https://www.independent.com/2007/12/08/ucsb-hosts-largest-computer-hacking-competition-ever/'
            },
            {
                name: 'CTFtime',
                type: 'website',
                url: 'https://ctftime.org/team/285'
             
            }
        ],
        description: 'Participated in numerous hacking competitions including DEFCON CTF in Las Vegas with the ShellPhish team (#2 in the world in 2025 according to CTFtime). Also helped design and organize the iCTF, the biggest academic hacking competition (back then) with more than 1,000 players globally, for four years.'
      },
      {
        title: 'European Space Agency Robotic Challenge',
        organization: 'European Space Agency',
        period: '2008',
            links: [

            {
                name: 'ESA',
                type: 'website',
                url: 'https://www.esa.int/Education/Germany_s_CESAR_crowned_king_of_rovers_in_ESA_s_Robotics_Challenge2'
            },
            {
                name: 'Robot selfie',
                type: 'website',
                url: 'https://4.bp.blogspot.com/_PZedSw-39RQ/SSqXB53sdSI/AAAAAAAAAAc/WuE0kscIj_4/s1600/pESApod_moon.jpg'
            }
        ],
        description: 'Built an hexapod robot with a student team. Won a €40k grant. European Space Agency\'s Robotics Challenge finalist'
      },
    ],
    awards: [
      {
        title: 'Pwnie Award',
        organization: '',
        period: '2017',
        description: 'For the Shattered project, breaking the SHA-1 hash function in practice.'
      },
      {
        title: 'Google Tech Award',
        organization: '',
        period: '2018',
        description: 'For the Credential Alerting system that automatically detects and disables leaked service account keys.'
      }
    ],
    selectedPublications: [
      {
        title: 'BareDroid: Large-Scale Analysis of Android Apps on Real Devices',
        authors: 'S. Mutti, Y. Fratantonio, A. Bianchi, J. Corbetta, L. Invernizzi, D. Kirat, C. Kruegel, G. Vigna',
        venue: 'Proceedings of the Annual Computer Security Applications Conference (ACSAC 2015)'
      },
      {
        title: 'What the App is That? Deception and Countermeasures in the Android User Interface',
        authors: 'A. Bianchi, J. Corbetta, L. Invernizzi, Y. Fratantonio, C. Kruegel, G. Vigna',
        venue: 'Proceedings of the IEEE Symposium on Security and Privacy (S&P 2015)'
      },
      {
        title: 'Nazca: Detecting Malware Distribution in Large-Scale Networks',
        authors: 'L. Invernizzi, S. Miskovic, R. Torres, S. Saha, S. Lee, M. Mellia, C. Kruegel, G. Vigna',
        venue: 'Proceedings of the ISOC Network and Distributed System Security Symposium (NDSS 2014)',
        award: 'UCSB Computer Science Outstanding Publication Award 2015'
      },
      {
        title: 'EVILSEED: A Guided Approach to Finding Malicious Web Pages',
        authors: 'L. Invernizzi, S. Benvenuti, P. Milani Comparetti, M. Cova, C. Kruegel, G. Vigna',
        venue: 'Proceedings of the IEEE Symposium on Security and Privacy (S&P 2012)',
        award: 'AT&T NYU CSAW best security paper \'12 finalist'
      }
    ],
    patents: [
      {
        title: 'Detecting Malware Infestations in Large-Scale Networks',
        authors: 'L. Invernizzi, S. Miskovic, R. Torres, S. Saha, S. Lee, M. Mellia, C. Kruegel, G. Vigna',
        number: 'United States Patent 8959643'
      }
    ],
    pressItems: [
      { title: 'New detection system spots zero-day malware', source: 'Net Security' },
      { title: 'Zoom out for a view of malware, say boffins', source: 'The Register' },
      { title: 'UCSB Security Researchers To Help Too-Trusting Smartphone App Users', source: 'Campus Technology' },
      { title: 'World\'s Largest Computer Hacking Contest Happening at UCSB', source: 'KEYT' },
      { title: 'Cyberteams duke it out in the World Series of hacking', source: 'CNBC' }
    ],
    contactInfo: [
      { type: 'email', value: 'luca@lucainvernizzi.net' },
      { type: 'twitter', value: '@invernizzi', link: 'https://twitter.com/invernizzi' },
      { type: 'linkedin', value: 'lucainvernizzi', link: 'https://www.linkedin.com/in/lucainvernizzi' },
      { type: 'github', value: 'invernizzi', link: 'https://github.com/invernizzi' }
    ]
  })
}) 
