name: Deploy to Cloudflare
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run lint
      - run: pnpm run typecheck
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - run: pnpm install
      - run: pnpm build:cloudflare
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3

        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

